// <auto-generated />
namespace TheTruck.Web.DataContexts.ProductMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSurvey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSurvey));
        
        string IMigrationMetadata.Id
        {
            get { return "201610100819594_AddSurvey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
